# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Hacker Rank
tagline:          "My personal attemp"
description:      ''
baseurl:	  "/hackerrank"
url:              "http://straktor.github.io/hackerrank"

author:
  name:           'straktor'
  url:            https://github.com/Straktor

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/Straktor/hackerrank
